services:
  _defaults:
    autowire: true
    autoconfigure: true

  Amir\MapParcel\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  Amir\MapParcel\Domain\ParcelaRepository:
    alias: Amir\MapParcel\Infrastructure\Tiling\TiledParcelaRepository

  Amir\MapParcel\Infrastructure\Cache\CachedParcelaRepository:
    arguments:
      $cache: '@cache.app'